### ISSUE TITLE
Difference from fluent-cat?

### ISSUE THREAD

**Issue by cemremengu** [davidedantonio/pino-fluentd#2]
Just curious, what are the main differences between piping through this utility vs piping through `fluent-cat` ?

**Comment by davidedantonio** [comment]
It's a good question!
The features are basically the same, but with this module you don't need to install fluentd, and it's dependencies, on the same instance where run your node.js/pino code. 
Another difference is that you can decide to send only the logs that really interest you using the `-l` flag.

That's all
:smile:

**Comment by cemremengu** [comment]
Thanks for the answer! I am relatively new with these technologies so trying to make sure I get everything right 😄

**Comment by davidedantonio** [comment]
@cemremengu thanks to you man! :pray:
